package vista;

import heuristica.CalcularDistanciaLineaRecta;
import heuristica.InterfazHeuristica;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;







import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.xml.parsers.FactoryConfigurationError;

import aStar.AEstrella;
import aStar.Camino;
import aStar.Mapa;
import aStar.Nodo;
import cronometro.Cronometro;

/**
 *
 * @author usuario_local
 */
public class MainWindow extends javax.swing.JFrame implements ActionListener{                   
	// Variables declaration - do not modify                     
	private javax.swing.JButton jButtonComenzar;
	private javax.swing.JButton jButtonReiniciar;
	private javax.swing.JLabel jLabelNombre;
	private javax.swing.JLabel jLabelFacultad;
	private javax.swing.JLabel jLabelInicio;
	private javax.swing.JLabel jLabelFinal;
	private javax.swing.JPanel panelTablero;
	private javax.swing.JTextField TextFieldIniX;
	private javax.swing.JTextField TextFieldIniY;
	private javax.swing.JTextField TextFieldFinX;
	private javax.swing.JTextField FinY;
	// End of variables declaration                  
	private CityMapPanel celdas;
	private Mapa map;
	InterfazHeuristica heuristic;
	AEstrella pathFinder;
	int[][] obstacleMap;
	Nodo nodo;
	////////////////////////////////
	/**
	 * Creates new form Principal
	 */
	public MainWindow(Mapa map, InterfazHeuristica h, AEstrella pathFinder) {
		celdas= new CityMapPanel();       
		this.map=map;
		heuristic=h;
		this.pathFinder=pathFinder;
		initComponents();

	}
	public MainWindow() {
		celdas= new CityMapPanel();
		celdas.inicializarEscuchadores(this);
		obstacleMap= new int[21][21];
		initComponents();       
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		this.setTitle("Algortimo A* - Rodrigo de Miguel González");
		jLabelNombre = new javax.swing.JLabel();
		jLabelFacultad = new javax.swing.JLabel();
		jButtonComenzar = new javax.swing.JButton();
		jButtonReiniciar = new javax.swing.JButton();
		TextFieldIniX = new javax.swing.JTextField("");
		TextFieldIniY = new javax.swing.JTextField("");
		TextFieldFinX = new javax.swing.JTextField("");
		FinY = new javax.swing.JTextField("");
		jLabelInicio = new javax.swing.JLabel();
		jLabelFinal = new javax.swing.JLabel();
		panelTablero = new javax.swing.JPanel();
		Font font = new Font("Futura", Font.BOLD,12);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabelNombre.setText("Rodrigo de Miguel González");
		jLabelNombre.setFont(font);
		jLabelFacultad.setText("Facultad Informatica - UCM");
		jLabelFacultad.setFont(font);
		jButtonComenzar.setText("Comenzar");
		jButtonReiniciar.setText("Reiniciar");
		//ImageIcon imgStart= new ImageIcon(this.getClass().getResource("/images/start.png"));
		//ImageIcon imgRestart= new ImageIcon(this.getClass().getResource("/images/restart.png"));
		//jButton1.setIcon(imgStart);
		//jButton2.setIcon(imgRestart);
		
	
		
		jLabelInicio.setText("Inicio:");
		jLabelInicio.setFont(font);
		jLabelFinal.setText("Final:");
		jLabelFinal.setFont(font);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(panelTablero);
		//********
		panelTablero.setBorder(BorderFactory.createLineBorder(Color.red));
		//******
		panelTablero.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(celdas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGap(0, 11, Short.MAX_VALUE)
						.addComponent(celdas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelFacultad)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addComponent(jLabelNombre)
										.addGap(18, 18, 18)))
										.addGap(5, 5, 5))
										.addGroup(layout.createSequentialGroup()
												.addContainerGap()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addComponent(jLabelInicio)
																.addGap(0, 0, Short.MAX_VALUE))
																.addGroup(layout.createSequentialGroup()
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(layout.createSequentialGroup()
																								.addComponent(jLabelFinal)
																								.addGap(57, 57, 57))
																								.addComponent(TextFieldIniY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addComponent(TextFieldIniX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addComponent(FinY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addComponent(jButtonComenzar, javax.swing.GroupLayout.Alignment.TRAILING)
																								.addComponent(jButtonReiniciar, javax.swing.GroupLayout.Alignment.TRAILING)
																								.addComponent(TextFieldFinX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(18, 18, 18)
																								.addComponent(panelTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
																								.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabelNombre)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabelFacultad)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabelInicio)
						.addGap(7, 7, 7)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(TextFieldIniX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(TextFieldIniY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(7, 7, 7)
										.addComponent(jLabelFinal)
										.addGap(2, 2, 2)
										.addComponent(TextFieldFinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(FinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(13, 13, 13)
										.addComponent(jButtonComenzar)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButtonReiniciar))

										.addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

										.addContainerGap())



				);
		
		jButtonReiniciar.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				restaurar();
			}
		});

		//////////////////////////////empezar////////////////////////////////////////
		jButtonComenzar.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				///comprobaciones que nos han puesto lo que nos tendrian que poner
				try{
					
				
				int xInicio=Integer.parseInt(TextFieldIniX.getText());
				int yInicio=Integer.parseInt(TextFieldIniY.getText());

				int xFinal=Integer.parseInt(TextFieldFinX.getText());
				int yFinal=Integer.parseInt(FinY.getText());
				
				if( xInicio > 19)
					JOptionPane.showMessageDialog(null, "Números del 0-19. Error en casilla X de Inicio" );
				else
					if( yInicio > 19)
						JOptionPane.showMessageDialog(null, "Números del 0-19. Error en casilla Y de Inicio" );
					else	
						if( xFinal > 19)
							JOptionPane.showMessageDialog(null, "Números del 0-19. Error en casilla X de Final" );
						else	
							if( yFinal > 19)
								JOptionPane.showMessageDialog(null, "Números del 0-19. Error en casilla Y de Final" );
							else{

									celdas.inicializarComienzoFin(xInicio, yInicio,xFinal,yFinal);
									// Inicializamos el mapa.
									map = new Mapa(21, 21, obstacleMap);				
									// Inicializamos la heurística.
									heuristic = new CalcularDistanciaLineaRecta();					
									// Inicializamos el algoritmo
									pathFinder = new AEstrella(map, heuristic);					
									// Calculamos el camino más corto.
									pathFinder.calcularCaminoMasCorto(xInicio, yInicio,xFinal,yFinal);
					
									Camino caminoMasCorto = pathFinder.getCaminoMasCorto();
									pintarCaminoCeldas(caminoMasCorto);
							}
			}catch(NumberFormatException e1 ){
				JOptionPane.showMessageDialog(null, "Lo que has introducido no es un número" );
			}	
			}
		});


		/////////////////////////////////////////////////////////////////////////////

		setSize(900, 800);

		setLocationRelativeTo(this);

		pack();
	}// </editor-fold>                        

	protected void pintarCaminoCeldas(final Camino caminoMasCorto) {
		// TODO Auto-generated method stub
		new Thread (new Runnable() {

			public void run() {
		if(caminoMasCorto == null){
			JOptionPane.showMessageDialog(null, "No existe un camino posible" );
			restaurar();
		} // no hay camino
		else
		for(int x=0; x < map.getMapWith(); x++) {

			for(int y=0; y<map.getMapHeight(); y++) {
				nodo = map.getNodo(x, y);

				 if (caminoMasCorto.contains(nodo.getX(), nodo.getY())) {	
					try {
						//Retardo para pintar celdas
						Thread.sleep(200);
						
						if(x < map.getMapWith()){
							celdas.pintarCelda(nodo.getX(), nodo.getY());	
						}
					} catch (InterruptedException e) {
					}

				} 
			}
			
				
		}
		int xFinal=Integer.parseInt(TextFieldFinX.getText());
		int yFinal=Integer.parseInt(FinY.getText());
		celdas.pintarFinal(xFinal, yFinal);
		}

		}).start();
	}
	protected void restaurar() {
		dispose();
		MainWindow p = new MainWindow();
		p.arranca();
	}

	public void arranca(){      

		// TODO Auto-generated method stub
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				setVisible(true);
			}
		});

	}
	public void actionPerformed(ActionEvent arg0) {
		// TODO Auto-generated method stub
		PlaceCell fuente = (PlaceCell) arg0.getSource(); // el que generó el evento
		celdas.pintarObstaculo(fuente.getFila(), fuente.getColumna());
		obstacleMap[fuente.getFila()][fuente.getColumna()]=1;
	}

}
